config/routes.rb
Rails.application.routes.draw do

  # You can have the root of your site routed with "root"
  root 'home#index'

  post 'run_test', to: 'home#run_test'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def run_test
    test_plan = TestPlan.new(params[:browser], params[:timeout], params[:cms], params[:email], params[:password])

    if test_plan.load_cms == true
      flash[:success] = "CMS Loaded as Expected"
    else
      flash[:notice] = "CMS Did Not Load"
    end

    redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <h1>QAndroid</h1>
    <p>An experimental integrated test suite -- designed to quickly peform basic tasks on the CMS.</p>
  </div>
</div>
<div class="container">
  <div class="col-md-6">
    <div class="jumbotron">
      <%= form_tag(run_test_path, method: "post") do %>
        <fieldset class="form-group">
          <%= label_tag(:cms, "CMS") %>
          <%= text_field_tag(:cms, "", class: 'form-control') %>
        </fieldset>
        <fieldset class="form-group">
          <%= label_tag(:browser, "Browser") %>
          <%= select_tag(:browser, options_for_select(["firefox", "chrome"]), class: 'form-control') %>
        </fieldset>
        <fieldset class="form-group">
          <%= label_tag(:timeout, "Timeout") %>
          <%= number_field_tag(:timeout, 15, class: 'form-control') %>
        </fieldset>
        <fieldset class="form-group">
          <%= label_tag(:email, "Email") %>
          <%= text_field_tag(:email, "", class: 'form-control') %>
        </fieldset>
        <fieldset class="form-group">
          <%= label_tag(:password, "Password") %>
          <%= password_field_tag(:password, "", class: 'form-control') %>
        </fieldset>
        <%= submit_tag("Run Test", class: 'btn btn-primary') %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QAndroid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
</div>

<%= yield %>

</body>
</html>